stages:
    - build
    - test
    - export
    - deploy

# https://gitlab.com/barichello/godot-ci
# https://docs.gitlab.com/ee/ci/yaml/

windows:
    image: barichello/godot-ci:$GODOT_VERSION
    stage: export
    tags:
        - docker
    script:
        - mkdir -v -p "$NAME-$CI_COMMIT_BRANCH"
        - cd "$NAME"
        - godot -v --export "Windows Desktop" ../"$NAME-$CI_COMMIT_BRANCH"/"$NAME.exe"
    artifacts:
        expire_in: 1 day
        paths:
            - "$NAME-$CI_COMMIT_BRANCH/"
        name:
            "$NAME-$CI_COMMIT_BRANCH-windows"

linux:
    image: barichello/godot-ci:$GODOT_VERSION
    stage: export
    tags:
        - docker
    script:
        - mkdir -v -p "$NAME-$CI_COMMIT_BRANCH"
        - cd "$NAME"
        - godot -v --export "Linux/X11" ../"$NAME-$CI_COMMIT_BRANCH"/"$NAME.x86_64"
    artifacts:
        expire_in: 1 day
        paths:
            - "$NAME-$CI_COMMIT_BRANCH/"
        name:
            "$NAME-$CI_COMMIT_BRANCH-linux"

mac:
    image: barichello/godot-ci:$GODOT_VERSION
    stage: export
    tags:
        - docker
    script:
        - mkdir -v -p "$NAME-$CI_COMMIT_BRANCH"
        - cd "$NAME"
        - godot -v --export "Mac OSX" ../"$NAME-$CI_COMMIT_BRANCH"/"$NAME.zip"
    artifacts:
        expire_in: 1 day
        paths:
            - "$NAME-$CI_COMMIT_BRANCH/"
        name:
            "$NAME-$CI_COMMIT_BRANCH-mac"


web:
    image: barichello/godot-ci:$GODOT_VERSION
    stage: export
    tags:
        - docker
    script:
        - mkdir -v -p "$NAME-$CI_COMMIT_BRANCH"
        - cd "$NAME"
        - godot -v --export "HTML5" ../"$NAME-$CI_COMMIT_BRANCH"/"$NAME.html"
    artifacts:
        expire_in: 1 day
        paths:
            - "$NAME-$CI_COMMIT_BRANCH/"
        name:
            "$NAME-$CI_COMMIT_BRANCH-web"
